platform :ios, '16.0'
use_frameworks!

workspace 'DouyinDemo'

target 'DouyinHostApp' do
  project 'Apps/DouyinHostApp/DouyinHostApp.xcodeproj'

  pod 'AWELaunchKit',     :path => './LaunchKit'
  pod 'AWEInfra',         :path => './Infra'
  pod 'AWEUIResources',   :path => './UIResources'
  pod 'AWEUITheme',       :path => './UITheme'
  pod 'AWESearch/Impl',   :path => './Modules/Search'
  pod 'AWEFeed/Impl',     :path => './Modules/Feed'
end

target 'SearchShellApp' do
  project 'Apps/SearchShellApp/SearchShellApp.xcodeproj'

  pod 'AWELaunchKit',     :path => './LaunchKit'
  pod 'AWEInfra',         :path => './Infra'
  pod 'AWEUIResources',   :path => './UIResources'
  pod 'AWEUITheme',        :path => './UITheme'
  pod 'AWESearch/Impl',   :path => './Modules/Search'
end

target 'FeedShellApp' do
  project 'Apps/FeedShellApp/FeedShellApp.xcodeproj'

  pod 'AWELaunchKit',     :path => './LaunchKit'
  pod 'AWEInfra',         :path => './Infra'
  pod 'AWEUIResources',   :path => './UIResources'
  pod 'AWEUITheme',       :path => './UITheme'
  pod 'AWEFeed/Impl',     :path => './Modules/Feed'
  pod 'AWESearch/Impl',   :path => './Modules/Search'
end

